version: "3.0"

services:
  suma:
    container_name: suma_web
    build:
      context: .
      dockerfile: Dockerfile-suma
    ports:
      - 80:80
      - 19679:19679

  mysql_db:
    container_name: suma_mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    env_file: .env
    ports:
        - 3306:3306
    volumes:
     - ./mountpoints/db:/opt/db
