version: "3.0"

services:
  suma:
    container_name: suma_web
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-suma
    ports:
      - 80:80
      - 19679:19679

  mysql_db:
    container_name: suma_mysql
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-mysql
    env_file: ./config/mysql.env
    ports:
        - 3306:3306
