# Copy this file to a new file `config.yaml`.
#
# You must modify the following:
#
#    production:
#        sumaserver:
#            db:
#                host: host location of your mysql database
#                dbname: suma mysql database name
#                user: suma mysql **application** account name
#                pword: suma mysql **application** account password
#                port: mysql port number
#            log:
#                path: path to log directory
#                name: sumaserver.log
#
#  * Be sure that the log directory specified in `sumaserver:log:path`
#  both exists and is **writable by the web server**.

production:
    sumaserver:
        db:
            host: suma_mysql  # This refers to the mysql container's name in the docker network.
            platform: Pdo_Mysql
            dbname: suma
            user: suma
            pword: "enter the user password from config/mysql.env"
            port: 3306
        log:
            path: /tmp
            name: sumaserver.log
        admin:  # For /sumaserver/admin
            user: "whatever you want the admin username to be"
            pass: "whatever you want the admin password to be"
    queryserver:
        db:
            limit: 10000

development:
    _extends: production
    sumaserver:
        db:
            dbname: sumadev
        log:
            path: /tmp
